#! /usr/bin/env node

const fs = require("fs");
const path = require("path");

// Path to where your scripts are stored.
const filesPath = path.resolve("/Users/aadhi/.js");

fs.readdir(filesPath, { withFileTypes: true }, (err, content) => {
  const files = content;
  files.forEach((file) => {
    if (
      !file.isDirectory() &&
      path.extname(file.name) === "" &&
      file.name !== ".gitignore" &&
      file.name !== "helpers"
    ) {
      console.log(file.name);
    }
  });
});
